spring:
  batch:
    jdbc:
      initialize-schema: always  # Creates BATCH_* tables in batch datasource
    job:
      enabled: false             # Disable auto-run; launch jobs manually or via scheduler
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for dev, 'validate' for prod
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

# Batch metadata datasource
batch:
  datasource:
    url: jdbc:mysql://localhost:3305/batch_metadata
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

# Source datasource (read from)
source:
  datasource:
    url: jdbc:mysql://localhost:3306/insuredportal
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

# Target datasource (write to)
target:
  datasource:
    url: jdbc:mysql://localhost:3305/payments
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
debug: true
